(cl:defpackage hw_3-srv
  (:use )
  (:export
   "CUSTOMTURTLEMOVEMENT"
   "<CUSTOMTURTLEMOVEMENT-REQUEST>"
   "CUSTOMTURTLEMOVEMENT-REQUEST"
   "<CUSTOMTURTLEMOVEMENT-RESPONSE>"
   "CUSTOMTURTLEMOVEMENT-RESPONSE"
  ))

