// Generated by gencpp from file hw_3/CustomTurtleMovement.msg
// DO NOT EDIT!


#ifndef HW_3_MESSAGE_CUSTOMTURTLEMOVEMENT_H
#define HW_3_MESSAGE_CUSTOMTURTLEMOVEMENT_H

#include <ros/service_traits.h>


#include <hw_3/CustomTurtleMovementRequest.h>
#include <hw_3/CustomTurtleMovementResponse.h>


namespace hw_3
{

struct CustomTurtleMovement
{

typedef CustomTurtleMovementRequest Request;
typedef CustomTurtleMovementResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CustomTurtleMovement
} // namespace hw_3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hw_3::CustomTurtleMovement > {
  static const char* value()
  {
    return "f0f2a6af04cef065d9ec88019ed73d34";
  }

  static const char* value(const ::hw_3::CustomTurtleMovement&) { return value(); }
};

template<>
struct DataType< ::hw_3::CustomTurtleMovement > {
  static const char* value()
  {
    return "hw_3/CustomTurtleMovement";
  }

  static const char* value(const ::hw_3::CustomTurtleMovement&) { return value(); }
};


// service_traits::MD5Sum< ::hw_3::CustomTurtleMovementRequest> should match
// service_traits::MD5Sum< ::hw_3::CustomTurtleMovement >
template<>
struct MD5Sum< ::hw_3::CustomTurtleMovementRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hw_3::CustomTurtleMovement >::value();
  }
  static const char* value(const ::hw_3::CustomTurtleMovementRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw_3::CustomTurtleMovementRequest> should match
// service_traits::DataType< ::hw_3::CustomTurtleMovement >
template<>
struct DataType< ::hw_3::CustomTurtleMovementRequest>
{
  static const char* value()
  {
    return DataType< ::hw_3::CustomTurtleMovement >::value();
  }
  static const char* value(const ::hw_3::CustomTurtleMovementRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hw_3::CustomTurtleMovementResponse> should match
// service_traits::MD5Sum< ::hw_3::CustomTurtleMovement >
template<>
struct MD5Sum< ::hw_3::CustomTurtleMovementResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hw_3::CustomTurtleMovement >::value();
  }
  static const char* value(const ::hw_3::CustomTurtleMovementResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hw_3::CustomTurtleMovementResponse> should match
// service_traits::DataType< ::hw_3::CustomTurtleMovement >
template<>
struct DataType< ::hw_3::CustomTurtleMovementResponse>
{
  static const char* value()
  {
    return DataType< ::hw_3::CustomTurtleMovement >::value();
  }
  static const char* value(const ::hw_3::CustomTurtleMovementResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HW_3_MESSAGE_CUSTOMTURTLEMOVEMENT_H
