// Generated by gencpp from file hw_3/CustomTurtleMovementRequest.msg
// DO NOT EDIT!


#ifndef HW_3_MESSAGE_CUSTOMTURTLEMOVEMENTREQUEST_H
#define HW_3_MESSAGE_CUSTOMTURTLEMOVEMENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hw_3
{
template <class ContainerAllocator>
struct CustomTurtleMovementRequest_
{
  typedef CustomTurtleMovementRequest_<ContainerAllocator> Type;

  CustomTurtleMovementRequest_()
    : movementType()
    , duration(0)  {
    }
  CustomTurtleMovementRequest_(const ContainerAllocator& _alloc)
    : movementType(_alloc)
    , duration(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _movementType_type;
  _movementType_type movementType;

   typedef int16_t _duration_type;
  _duration_type duration;





  typedef boost::shared_ptr< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CustomTurtleMovementRequest_

typedef ::hw_3::CustomTurtleMovementRequest_<std::allocator<void> > CustomTurtleMovementRequest;

typedef boost::shared_ptr< ::hw_3::CustomTurtleMovementRequest > CustomTurtleMovementRequestPtr;
typedef boost::shared_ptr< ::hw_3::CustomTurtleMovementRequest const> CustomTurtleMovementRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator1> & lhs, const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator2> & rhs)
{
  return lhs.movementType == rhs.movementType &&
    lhs.duration == rhs.duration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator1> & lhs, const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hw_3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30c83df51c111841973f920502f5ff93";
  }

  static const char* value(const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30c83df51c111841ULL;
  static const uint64_t static_value2 = 0x973f920502f5ff93ULL;
};

template<class ContainerAllocator>
struct DataType< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hw_3/CustomTurtleMovementRequest";
  }

  static const char* value(const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string movementType\n"
"int16 duration\n"
;
  }

  static const char* value(const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.movementType);
      stream.next(m.duration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomTurtleMovementRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hw_3::CustomTurtleMovementRequest_<ContainerAllocator>& v)
  {
    s << indent << "movementType: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.movementType);
    s << indent << "duration: ";
    Printer<int16_t>::stream(s, indent + "  ", v.duration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HW_3_MESSAGE_CUSTOMTURTLEMOVEMENTREQUEST_H
